name = "nowall-redirect"
main = "src/index.js"
compatibility_date = "2023-05-18"

[assets]
directory = "./public"
binding = "ASSETS"

# Development environment
[env.dev]
workers_dev = true

# Production environment
[env.production]
workers_dev = true
routes = [
  { pattern = "nowall.cc", custom_domain = true }
]